server:
  port: 9092

logging:
  level:
    root: INFO
    com.codingshuttle.projects.lovable_clone: INFO   # or DEBUG if you want more
spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:postgresql://localhost:5432/lovable
    username: kumkumjain
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update     # << Added DDL Auto here (create / update / validate / none)
    show-sql: true          # Shows SQL queries in console
    properties:
      hibernate:
        format_sql: true    # Pretty format SQL queries
        use_sql_comments: true  # Adds comments to SQL queries
